version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME:-auth_db}
      POSTGRES_USER: ${AUTH_DB_USER:-auth}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data


  postgres-report:
    image: postgres:15
    container_name: postgres-report
    environment:
      POSTGRES_DB: ${REPORT_DB_NAME:-report_db}
      POSTGRES_USER: ${REPORT_DB_USER:-report}
      POSTGRES_PASSWORD: ${REPORT_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - report_data:/var/lib/postgresql/data

  postgres-portfolio:
    image: postgres:15
    container_name: postgres-portfolio
    environment:
      POSTGRES_DB: ${PORTFOLIO_DB_NAME:-portfolio_db}
      POSTGRES_USER: ${PORTFOLIO_DB_USER:-portfolio}
      POSTGRES_PASSWORD: ${PORTFOLIO_DB_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - portfolio_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  portfolio-service:
    build: ./portfolio-service
    depends_on:
      - postgres-portfolio
      - kafka
    ports:
      - "8084:8084"
    environment:
      DB_URL: jdbc:postgresql://postgres-portfolio:5432/portfolio_db
      DB_USERNAME: portfolio
      DB_PASSWORD: portfolio
      JWT_SECRET: ${JWT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres-auth
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      DB_USERNAME: auth
      DB_PASSWORD: auth
      JWT_SECRET: ${JWT_SECRET}

  report-service:
    build: ./report-service
    depends_on:
      - postgres-report
      - kafka
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:postgresql://postgres-report:5432/report_db
      DB_USERNAME: report
      DB_PASSWORD: report
      JWT_SECRET: ${JWT_SECRET}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

volumes:
  auth_data:
  report_data:
  portfolio_data:

